[project]
name = "Scripts"
version = "0.1.0"
description = "Dice tester"
dependencies = [
    "ultralytics>=8.4.7"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.12"]

[project.urls]
Home = "https://github.com/G-IV/Dice_Tester"